---
trigger:
  - main
pr:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest
variables:
  - group: 


stages:
  - stage: Test
    jobs:
      - job: codebeamer
        timeoutInMinutes: 10 # how long to run the job before automatically cancelling
        cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
        displayName: codebeamer upload
        steps:
          - script: |
              echo "Empty job."
          - task: codeBeamer@1
            inputs:
              test_xml_folder: example/test_results
              test_run_name: $(Build.DefinitionName) $(Build.Reason)
              test_run_id: $(Build.BuildId)
              server_url: http://192.168.10.90:8083/cb
              cb_user: $(cb_user)
              cb_password: $(cb_password)
              test_configuration_id: "2143"
              test_case_tracker_id: "14156"
              test_run_tracker_id: "14159"


