---
trigger:
  - main
pr:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest
variables:
  - group: secrets
stages:
  - stage: Test
    jobs:
      - job: codebeamer
        timeoutInMinutes: 10
        cancelTimeoutInMinutes: 2
        displayName: codebeamer upload
        steps:
          - script: |
              echo "Empty job."
          - task: codeBeamer@1
            inputs:
              test_xml_folder: example/test_results
              test_run_name: $(Build.DefinitionName) $(Build.Reason)
              test_run_id: $(Build.BuildId)
              server_url: http://localhost:8080/cb/user
              cb_user: $(cb_user)
              cb_password: $(cb_password)
              test_configuration_id: "1000"
              test_case_tracker_id: "3388"
              test_run_tracker_id: "3391"